{
    "docs": "https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/validate-modules.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/validate-modules.html)] failed with 58 errors:", 
            "output": "plugins/modules/veeam_vbr_credentials.py:0:0: doc-choices-do-not-match-spec: Argument 'state' in argument_spec defines choices as (['absent', 'present']) but documentation defines choices as ([])\nplugins/modules/veeam_vbr_credentials.py:0:0: doc-choices-do-not-match-spec: Argument 'type' in argument_spec defines choices as (['Windows', 'Linux', 'Standard']) but documentation defines choices as (['windows', 'linux', 'standard'])\nplugins/modules/veeam_vbr_credentials.py:0:0: doc-default-does-not-match-spec: Argument 'state' in argument_spec defines default as ('present') but documentation defines default as (None)\nplugins/modules/veeam_vbr_credentials.py:0:0: doc-default-does-not-match-spec: Argument 'type' in argument_spec defines default as ('Standard') but documentation defines default as ('standard')\nplugins/modules/veeam_vbr_credentials.py:0:0: invalid-documentation: DOCUMENTATION.description: expected a list for dictionary value @ data['description']. Got None\nplugins/modules/veeam_vbr_credentials.py:0:0: invalid-documentation: DOCUMENTATION.short_description: expected str for dictionary value @ data['short_description']. Got None\nplugins/modules/veeam_vbr_credentials.py:0:0: missing-python-interpreter: Interpreter line is not \"#!/usr/bin/python\"\nplugins/modules/veeam_vbr_credentials.py:0:0: parameter-type-not-in-doc: Argument 'description' in argument_spec defines type as 'str' but documentation doesn't define type\nplugins/modules/veeam_vbr_credentials.py:0:0: parameter-type-not-in-doc: Argument 'id' in argument_spec defines type as 'str' but documentation doesn't define type\nplugins/modules/veeam_vbr_credentials.py:0:0: parameter-type-not-in-doc: Argument 'password' in argument_spec defines type as 'str' but documentation doesn't define type\nplugins/modules/veeam_vbr_credentials.py:0:0: parameter-type-not-in-doc: Argument 'state' in argument_spec defines type as 'str' but documentation doesn't define type\nplugins/modules/veeam_vbr_credentials.py:0:0: parameter-type-not-in-doc: Argument 'tag' in argument_spec defines type as 'str' but documentation doesn't define type\nplugins/modules/veeam_vbr_credentials.py:0:0: parameter-type-not-in-doc: Argument 'username' in argument_spec defines type as 'str' but documentation doesn't define type\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.SSHPort: extra keys not allowed @ data['msg']['SSHPort']. Got 22\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.addToSudoers: extra keys not allowed @ data['msg']['addToSudoers']. Got False\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.autoElevated: extra keys not allowed @ data['msg']['autoElevated']. Got False\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.creationDateTime: extra keys not allowed @ data['msg']['creationDateTime']. Got '07.10.2020 00:08:45'\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.id: extra keys not allowed @ data['msg']['id']. Got '317da5a8-3d12-428b-b1d7-95e9e780bb14'\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.passphrase: extra keys not allowed @ data['msg']['passphrase']. Got ''\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.privateKey: extra keys not allowed @ data['msg']['privateKey']. Got ''\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.returned: required key not provided @ data['msg']['returned']. Got None\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.tag: extra keys not allowed @ data['msg']['tag']. Got '6b8ced39-4e37-4b95-8e8c-8179a3dcfab5'\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.type: not a valid value for dictionary value @ data['msg']['type']. Got 'Linux'\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.useSu: extra keys not allowed @ data['msg']['useSu']. Got False\nplugins/modules/veeam_vbr_credentials.py:0:0: return-syntax-error: RETURN.msg.username: extra keys not allowed @ data['msg']['username']. Got 'root'\nplugins/modules/veeam_vbr_credentials.py:0:0: undocumented-parameter: Argument 'description' is listed in the argument_spec, but not documented in the module documentation\nplugins/modules/veeam_vbr_credentials.py:0:0: undocumented-parameter: Argument 'id' is listed in the argument_spec, but not documented in the module documentation\nplugins/modules/veeam_vbr_credentials.py:0:0: undocumented-parameter: Argument 'password' is listed in the argument_spec, but not documented in the module documentation\nplugins/modules/veeam_vbr_credentials.py:0:0: undocumented-parameter: Argument 'state' is listed in the argument_spec, but not documented in the module documentation\nplugins/modules/veeam_vbr_credentials.py:0:0: undocumented-parameter: Argument 'tag' is listed in the argument_spec, but not documented in the module documentation\nplugins/modules/veeam_vbr_credentials.py:0:0: undocumented-parameter: Argument 'username' is listed in the argument_spec, but not documented in the module documentation\nplugins/modules/veeam_vbr_credentials_info.py:0:0: invalid-documentation: DOCUMENTATION.description: expected a list for dictionary value @ data['description']. Got None\nplugins/modules/veeam_vbr_credentials_info.py:0:0: invalid-documentation: DOCUMENTATION.short_description: expected str for dictionary value @ data['short_description']. Got None\nplugins/modules/veeam_vbr_credentials_info.py:0:0: missing-python-interpreter: Interpreter line is not \"#!/usr/bin/python\"\nplugins/modules/veeam_vbr_credentials_info.py:0:0: return-syntax-error: RETURN.msg.data: extra keys not allowed @ data['msg']['data']. Got [{'SSHPort': 22, 'addToSudoers': False, 'autoElevated': False, 'creationDateTime': '06.10.2020 20:05:57', 'description': 'Helper appliance credentials', 'id': '70275b03-e805-49e1-9535-1867c62371e2', 'passphrase': '', 'privateKey': '', 'tag': '70275B03-E805-49E1-9535-1867C62371E2', 'type': 'Linux', 'useSu': False, 'username': 'root'}, {'creationDateTime': '06.10.2020 18:05:22', 'description': 'Tenant-side network extension appliance credentials', 'id': 'b5ebaf50-1a63-4c48-839f-5f8a5452520b', '...\nplugins/modules/veeam_vbr_credentials_info.py:0:0: return-syntax-error: RETURN.msg.description: required key not provided @ data['msg']['description']. Got None\nplugins/modules/veeam_vbr_credentials_info.py:0:0: return-syntax-error: RETURN.msg.pagination: extra keys not allowed @ data['msg']['pagination']. Got {'total': 0}\nplugins/modules/veeam_vbr_credentials_info.py:0:0: return-syntax-error: RETURN.msg.returned: required key not provided @ data['msg']['returned']. Got None\nplugins/modules/veeam_vbr_credentials_info.py:0:0: return-syntax-error: RETURN.msg.type: required key not provided @ data['msg']['type']. Got None\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: invalid-documentation: DOCUMENTATION.description: expected a list for dictionary value @ data['description']. Got None\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: invalid-documentation: DOCUMENTATION.short_description: expected str for dictionary value @ data['short_description']. Got None\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: missing-python-interpreter: Interpreter line is not \"#!/usr/bin/python\"\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: return-syntax-error: RETURN.infrastructure_managedservers.data: extra keys not allowed @ data['infrastructure_managedservers']['data']. Got [{'credentialsId': '00000000-0000-0000-0000-000000000000', 'description': 'Backup server', 'id': '6745a759-2205-4cd2-b172-8ec8f7e60ef8', 'name': 'WIN-RT26QHK0M11', 'networkSettings': {'components': [{'componentName': 'DeployerSvc', 'port': 6160}, {'componentName': 'Transport', 'port': 6162}, {'componentName': 'Nfs', 'port': 6161}, {'componentName': 'RestoreProxy', 'port': 6170}, {'componentName': 'WanAccelerator', 'port': 6164}, {'componentName': 'Tape', 'port': 6166}, {'componentName': 'Clou...\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: return-syntax-error: RETURN.infrastructure_managedservers.description: required key not provided @ data['infrastructure_managedservers']['description']. Got None\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: return-syntax-error: RETURN.infrastructure_managedservers.pagination: extra keys not allowed @ data['infrastructure_managedservers']['pagination']. Got {'total': 1}\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: return-syntax-error: RETURN.infrastructure_managedservers.returned: required key not provided @ data['infrastructure_managedservers']['returned']. Got None\nplugins/modules/veeam_vbr_managedservers_info.py:0:0: return-syntax-error: RETURN.infrastructure_managedservers.type: required key not provided @ data['infrastructure_managedservers']['type']. Got None\nplugins/modules/veeam_vbr_repositories_info.py:0:0: invalid-documentation: DOCUMENTATION.description: expected a list for dictionary value @ data['description']. Got None\nplugins/modules/veeam_vbr_repositories_info.py:0:0: invalid-documentation: DOCUMENTATION.short_description: expected str for dictionary value @ data['short_description']. Got None\nplugins/modules/veeam_vbr_repositories_info.py:0:0: missing-python-interpreter: Interpreter line is not \"#!/usr/bin/python\"\nplugins/modules/veeam_vbr_repositories_info.py:0:0: return-syntax-error: RETURN.infrastructure_repositories.data: extra keys not allowed @ data['infrastructure_repositories']['data']. Got [{'description': 'Created by Veeam Backup', 'hostId': '6745a759-2205-4cd2-b172-8ec8f7e60ef8', 'id': '88788f9e-d8f5-4eb4-bc4f-9b3f5403bcec', 'kind': 'Das', 'mountServer': {'mountServerId': '6745a759-2205-4cd2-b172-8ec8f7e60ef8', 'vPowerNFSEnabled': True, 'vPowerNFSPortSettings': {'mountPort': 1058, 'vPowerNFSPort': 1058}, 'writeCacheFolder': ''}, 'name': 'Default Backup Repository', 'repository': {'advancedSettings': {'alignDataBlocks': True, 'decompressBeforeStoring': False, 'perVmBackup': Fa...\nplugins/modules/veeam_vbr_repositories_info.py:0:0: return-syntax-error: RETURN.infrastructure_repositories.description: required key not provided @ data['infrastructure_repositories']['description']. Got None\nplugins/modules/veeam_vbr_repositories_info.py:0:0: return-syntax-error: RETURN.infrastructure_repositories.pagination: extra keys not allowed @ data['infrastructure_repositories']['pagination']. Got {'total': 1}\nplugins/modules/veeam_vbr_repositories_info.py:0:0: return-syntax-error: RETURN.infrastructure_repositories.returned: required key not provided @ data['infrastructure_repositories']['returned']. Got None\nplugins/modules/veeam_vbr_repositories_info.py:0:0: return-syntax-error: RETURN.infrastructure_repositories.type: required key not provided @ data['infrastructure_repositories']['type']. Got None\nplugins/modules/veeam_vbr_servercertificate_info.py:0:0: documentation-error: Unknown DOCUMENTATION error, see TRACE: while parsing a flow mapping\n  in \"<unicode string>\", line 3, column 8\ndid not find expected ',' or '}'\n  in \"<unicode string>\", line 14, column 1\nplugins/modules/veeam_vbr_servercertificate_info.py:0:0: missing-python-interpreter: Interpreter line is not \"#!/usr/bin/python\"\nplugins/modules/veeam_vbr_servercertificate_info.py:65:1: return-syntax-error: RETURN is not valid YAML"
        }
    ], 
    "verified": false
}
